version: '3.1'

services:
  backend:
    #restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 9000:9000
    depends_on:
      - mysql

  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: beerPass
      MYSQL_PASSWORD: beerPass
      MYSQL_DATABASE: beerPass

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8888:80
    environment:
      PMA_HOST: beerPass
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      - mysql
    volumes:
      - mysqlDatabase:/var/lib/mysql

volumes:
  mysqlDatabase:
